### ISSUE TITLE
The calculation of accuracy is different from original perl script

### ISSUE THREAD

**Issue by positivepeng** [kaniblu/conlleval#1]
in \_\_main\_\_.py, the function “report", t`acc = stats['correct'] / stats['all']`, stats['correct'] is the number of correctly identified chunks, but stats["all"] is the number of token.

**Comment by kaniblu** [comment]
Thanks for the bug report. Actually, the calculation was off because `stats["correct"]` should have  been the count of correct tags. The denominator was fine.
