### ISSUE TITLE
Convenience function

### ISSUE THREAD

**Issue by kqf** [kaniblu/conlleval#2]
Hi, thanks for taking your time and making a python package for this script :D 

Is it possible to add a convenience function to your code that accepts two lists of labels? Now I have to do it on my own:

```python
from conlleval import evaluate as conll_lines


def coll_score(y_true, y_pred, metrics=("f1", "prec", "rec"), **kwargs):
    lines = [f"dummy XXX {t} {p}" for pair in zip(y_true, y_pred)
             for t, p in zip(*pair)]
    res = conll_lines(lines)
    return [res["overall"]["tags"]["evals"][m] for m in metrics]

```
Perhaps it's possible to add something like this to the existing code.

**Comment by kaniblu** [comment]
Definitely. The package was initially designed to preserve the functionality of the original script, but making it more friendly towards pythonic objects is the right way to go. If anyone is interested, pull requests are more than welcomed!
